name: "Build PDF"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v22
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
        extra_nix_config: "store = /home/runner/nix"
    - name: Cache Nix
      uses: actions/cache@v3.3.0
      with:
        key: ${{ hashfiles('flake.nix') }}
        path: ~/nix
    - run: nix build '.#nactl'
    - run: cp /home/runner/nix$(realpath result) nactl.pdf
    - run: nix build '.#kactl'
    - run: cp /home/runner/nix$(realpath result) kactl.pdf
    - run: nix build '.#nactl-complete'
    - run: cp /home/runner/nix$(realpath result) nactl-complete.pdf
    - uses: actions/upload-artifact@v3
      with:
        name: PDFs
        path: |
          nactl.pdf
          kactl.pdf
          nactl-complete.pdf
